trigger:
  branches:
    include:
    - main
  paths:
    include:
    - tfcode/lothslair-network/*
    - workflow/lothslair-network/lothslair-iac-tf-deploy.yml

extends:
  template: ../templates/pipeline/terraform.yaml
  parameters:
    environments:
      - name: dev
        workingDir: "$(System.DefaultWorkingDirectory)/tfcode/lothslair-network/"
        paramsDir: "$(System.DefaultWorkingDirectory)/tfcode/lothslair-network/params/"
        serviceConnectionName: 'LothLair-IaC-Terraform'
        tfStateRGName: 'rg-terraform'
        tfStateStorageAccountName: 'sttfdata13669'
        tfStateContainerName: 'tfstate'
        tfStateKeyName: 'dev-network'
