parameters:
  - name: environments
    displayName: 'List of Environments to Deploy To'
    type: object
  - name: operation
    displayName: 'Terraform Operation to Complete'
    type: string
    default: 'apply'
    values:
    - apply
    - destroy

variables:
  - name: operation_template
    ${{ if eq( parameters['operation'], 'destroy') }}:
       value: "../stage/terraformPlanDestroy.yaml"
    ${{ else }}:
     value: "../stage/terraformPlanApply.yaml"

stages:
- ${{ each environment in parameters.environments }}:
  - template: ${{ variables.operation_template }}
    parameters:
      environmentName: ${{ environment.name }}
      workingDir: ${{ environment.workingDir }}
      paramsDir: ${{ environment.paramsDir }}
      serviceConnectionName: ${{ environment.serviceConnectionName }}
      tfStateRGName: ${{ environment.tfStateRGName }}
      tfStateStorageAccountName: ${{ environment.tfStateStorageAccountName }}
      tfStateContainerName: ${{ environment.tfStateContainerName }}
      tfStateKeyName: ${{ environment.tfStateKeyName }}